name: Auto Update Gradle Dependencies

on:
  schedule:
    # This cron syntax runs the workflow every 6 hours
    - cron: '0 */6 * * *'  # Runs every 6 hours on the hour
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java (Gradle) environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'openjdk'

      # Install Gradle wrapper validation
      - name: Set up Gradle
        uses: gradle/wrapper-validation-action@v1

      # Run Gradle dependency updates task
      - name: Update Gradle dependencies
        run: ./gradlew dependencyUpdates -Drevision=release

      # Commit and push changes to build.gradle
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add build.gradle
          git commit -m "Auto update Gradle dependencies"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
