name: Auto Update Maven Dependencies

on:
  schedule:
    # This cron syntax runs the workflow every 6 hours
    - cron: '0 */6 * * *'  # Runs every 6 hours on the hour
  workflow_dispatch:  # Allows manual trigger via GitHub UI

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Java (Maven) environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Update Maven dependencies (adjust according to your needs)
      - name: Update Maven dependencies
        run: mvn versions:use-latest-releases -DallowSnapshots=false

      # Commit and push changes to pom.xml
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add pom.xml
          git commit -m "Auto update Maven dependencies"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
